### ISSUE TITLE
Python API order of torsion angle output

### ISSUE THREAD

**Issue by mheinzinger** [steineggerlab/foldcomp#48]
Hi,
first of all: thanks for this great work and for making it publicly available! :)
I am currently looking at the PDB structure 6EQW which I parsed using your foldcomp python API.
With this, I wanted to get some more information on the torsion angles which I read from you docu can either be accessed separately `data_dict["phi"]` or all together `data_dict["torsion_angles"]`. From your docu, I read that the sorting of the angles when extracted all together should be `(phi + psi + omega)`. However, when comparing the output of `data_dict["torsion_angles"]` and the output of the individual fields `data_dict["phi"]`, I get the impression that the order is rather  `(psi + omega + phi)`.
Am I misreading your docu here or is there maybe a misalignment between the docu and the actual output?

Best,
Michael

**Comment by khb7840** [comment]
I'll check the issue. Thank you for notifying this!

**Comment by mheinzinger** [comment]
Great, thanks.
Along the same lines (related but I can still open a new issue if that makes your life easier):
We compared the angles output by foldcomp to those produced by biopython (essentially, using [this notebook](https://gist.github.com/NatureGeorge/0fa075945d4b8ce75dc8113e37f1fb5c) and DSSP using PDB=6t1i (I also tried two other PDB structures but the trend was identical). Biopython and DSSP agreed on the output angles. Foldcomp also produced the same numerical angles but with the following off-sets:
- Phi angles have two additional elements at the end. So while DSSP/biopython give me e.g. [106, 42, ..., 55], foldcomp gives me [106, 42, ..., 55, 71, 89]
- Psi angles are 1-off/shifted from the start. As example, your script provides a list with [127, 121, 161, ...] and foldcomp gives me a list of [-40, 127, 121, 161, ...], i.e., the foldcomp output has one more element at the beginning.

Probably there is a reason for this (or I made a mistake) but could you explain this discrepancy?

**Comment by khb7840** [comment]
In Foldcomp, torsion angles are handled in the order of "phi-omega-psi" because 
only N, CA and C atoms are saved as backbone atoms. 
As the phi angle is defined as the angle between the planes formed by the atoms C-N-CA and N-CA-C,
phi angle of the N-terminal residue cannot be calculated directly with only N, CA and C atoms.
Other libraries utilize H atom to calculate the very first phi angle, but Foldcomp does not.
(http://www.mlb.co.jp/linux/science/garlic/doc/commands/dihedrals.html)
Similarly, the psi angle of the C-terminal residue is not calculated in Foldcomp.

The array of backbone atoms and torsion angles look like this in Foldcomp.
```
backbone = [N1, CA1, C1, N2, CA2, C2, ... , Nn-1, CAn-1,Cn-1, Nn, CAn, Cn] (length = 3 * N_RESIDUES)
```
```
psi = [N1-CA1-C1-N2, N2-CA2-C2-N3, ... , Nn-1-CAn-1-Cn-1-Nn] (length = N_RESIDUES - 1)
omega = [CA1-C1-N2-CA2, CA2-C2-N3-CA3, ..., CAn-1-Cn-1-Nn-CAn] (length = N_RESIDUES - 1)
phi = [C1-N2-CA2-C2, C2-N3-CA3-C3, ..., Cn-1-Nn-CAn-Cn] (length = N_RESIDUES - 1)
# torsion_angles = concatenate in the order of psi, omega, phi
```
I've checked 6tli.pdb and the torsion angles are calculated as described above.
I wish this helps you utilize the torsion angles in Foldcomp and if you have any suggestions, please let me know.

Sincerely,
Hyunbin Kim

**Comment by mheinzinger** [comment]
Nice, thanks for the details! :) 
I think with this, we can move forward. I'll re-open in case sth remains unclear.
Thanks again for your quick help & have a nice day
